version: "3.2"
services:
  php:
    build: 
      context: .
    image: thanhhao98/web-php-ass2:latest
    networks:
      - frontend
      - backend
    volumes:
            - ./src/:/var/www/html/
    ports:
      - "30001:80"
    container_name: phpApp
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=Admin!123
      - MYSQL_USER=haophan
      - MYSQL_PASSWORD=977463
      - MYSQL_DATABASE=Ass2
    container_name: sqlService 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=sqlService
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpAdminService
networks:
  frontend:
  backend:
